from datetime import datetime, timedelta
from jose import jwt, JWTError
import os
from dotenv import load_dotenv
from utils.logger import logger

load_dotenv()  # loads .env into environment
# GENERATED BY secret_key_generator from utils/generator
SECRET_KEY = os.getenv("SECRET_KEY")
# Encryption Algorithm
ALGORITHM = os.getenv("ALGORITHM")
TIME_HOURS = int(os.getenv("TIME_HOURS"))

def create_token(data: dict):
    payload = data.copy()
    payload["exp"] = datetime.now() + timedelta(hours=TIME_HOURS)
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)


def verify_token(token: str):
    try:
        logger.info("Decoding Token")
        return jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
    except JWTError:
        logger.error("Invalid Token")
        return None